# Generated by Django 3.1 on 2021-03-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Желаемая должность')),
                ('salary_min', models.IntegerField(blank=True, verbose_name='Минимальная зарплата')),
                ('salary_max', models.IntegerField(blank=True, verbose_name='Максимальная зарплата')),
                ('currency', models.CharField(blank=True, max_length=3, verbose_name='Валюта')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления резюме')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления резюме')),
                ('key_skills', models.CharField(blank=True, max_length=256, verbose_name='Ключевые навыки')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('opened', 'открыт')], max_length=16, verbose_name='Статус')),
                ('is_active', models.BooleanField(verbose_name='Активный')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, verbose_name='Название компании')),
                ('from_date', models.DateField(verbose_name='Начало работы')),
                ('to_date', models.DateField(blank=True, verbose_name='Конец работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(verbose_name='Активный')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseekerapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_type', models.CharField(max_length=32, verbose_name='Тип образования')),
                ('degree', models.CharField(max_length=64, verbose_name='Степень')),
                ('institution_name', models.CharField(max_length=64, verbose_name='Название учреждения')),
                ('from_date', models.DateField(verbose_name='Начало периода')),
                ('to_date', models.DateField(blank=True, verbose_name='Конец периода')),
                ('course_name', models.CharField(max_length=256, verbose_name='Название курса/кафедры')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(verbose_name='Активный')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseekerapp.resume', verbose_name='Резюме')),
            ],
        ),
    ]
