# Generated by Django 3.1 on 2021-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0004_auto_20210313_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
