# Generated by Django 3.1.1 on 2021-04-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0009_auto_20210412_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.TextField(blank=True, default='', help_text='поле необязательное', verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='key_skills',
            field=models.TextField(blank=True, default='', help_text='поле необязательное', verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='to_date',
            field=models.DateField(blank=True, help_text='оставьте пустым если работаете по настоящее время', null=True, verbose_name='Конец работы'),
        ),
    ]
