# Generated by Django 3.1.1 on 2021-04-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0010_auto_20210420_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeeducation',
            old_name='description',
            new_name='edu_description',
        ),
        migrations.RenameField(
            model_name='resumeexperience',
            old_name='to_date',
            new_name='finish_date',
        ),
        migrations.RenameField(
            model_name='resumeexperience',
            old_name='description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='resumeexperience',
            old_name='from_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary_max',
            field=models.IntegerField(blank=True, help_text='поле необязательное', null=True, verbose_name='Максимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary_min',
            field=models.IntegerField(blank=True, help_text='поле необязательное', null=True, verbose_name='Минимальная зарплата'),
        ),
    ]
