# Generated by Django 3.1 on 2021-03-07 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, unique=True, verbose_name='название компании')),
                ('tax_number', models.IntegerField(max_length=16, verbose_name='ИНН компании')),
                ('phone_number', models.IntegerField(blank=True, max_length=11, verbose_name='телефон')),
                ('site', models.CharField(blank=True, max_length=32, verbose_name='сайт компании')),
                ('industry_type', models.CharField(max_length=32, verbose_name='тип отрасли компании')),
                ('short_description', models.TextField(verbose_name='краткое описание компании')),
                ('logo', models.ImageField(blank=True, upload_to='company_logo')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='город расположения компании')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
