# Generated by Django 3.1 on 2021-03-07 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('middle_name', models.CharField(max_length=32, verbose_name='отчество')),
                ('gender', models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=16, verbose_name='пол')),
                ('birthday', models.DateField(verbose_name='дата рождения')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('married_status', models.CharField(choices=[('h', 'холост'), ('m', 'замужем/женат'), ('d', 'разведен/разведена')], max_length=1, verbose_name='Статус в браке')),
                ('photo', models.ImageField(blank=True, upload_to='jobseeker_photo')),
                ('phone_number', models.CharField(max_length=11, verbose_name='телефон')),
                ('about', models.TextField(blank=True, max_length=512, verbose_name='о себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name_plural': 'Работодатели'},
        ),
        migrations.RemoveField(
            model_name='employer',
            name='id',
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
