# Generated by Django 3.1 on 2021-03-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210308_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
    ]
