# Generated by Django 3.1.1 on 2021-04-20 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210412_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 7, 47, 31, 471018)),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 7, 47, 31, 477794)),
        ),
    ]
